name: Deploy example express-app to Amazon ECS
#
on:
    push:
        branches:
            - develop
jobs:
   deploy:
    uses: alex-zissis/workflows/.github/workflows/ecs-deploy.yml@develop
    with:
      application-name: express-app
      ecs-cluster: ecs-cluster-main
      image-tag: ${{ github.sha }}
      healthcheck-url: https://example.api.zico.dev/health
      ecr-registry: 921344595439.dkr.ecr.ap-southeast-2.amazonaws.com
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
