name: Deploy example express-app to Amazon ECS
#trigger
on:
    push:
        branches:
            - master
jobs:
   deploy:
    uses: alex-zissis/workflows/.github/workflows/ecs-deploy.yml@master
    
    with:
      username: mona
      application-name: express-app
      ecs-cluster: ecs-cluster-main
      image-tag: ${{ github.sha }}
      healthcheck-url: https://example.api.zico.dev/health
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
