name: PR Checks

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
   build-and-test:
      uses: alex-zissis/workflows/.github/workflows/build-and-test-container.yml@develop
      with:
        application-name: express-app
        run-tests: "0"
        app-path: ./examples/express-app
